const GET_FOLDERS = "GET_FOLDERS";
const LOADING_FOLDERS = "LOADING_FOLDERS";
const FOLDER_FETCH_ERROR = "FOLDER_FETCH_ERROR";
const SELECT_FOLDER = "SELECT_FOLDER";

const GET_MAILS = "GET_MAILS";
const LOADING_MAILS = "LOADING_MAILS";
const MAILS_FETCH_ERROR = "MAILS_FETCH_ERROR";
const SELECT_MAIL = "SELECT_MAIL";

const GET_MAIL = "GET_MAIL";
const NEW_MAIL = "NEW_MAIL";
const LOADING_MAIL = "LOADING_MAIL";
const MAIL_FETCH_ERROR = "MAIL_FETCH_ERROR";

const GET_CONTACTS = 'GET_CONTACTS'
const LOADING_CONTACTS = 'LOADING_CONTACTS'
const CONTACTS_FETCH_ERROR = 'CONTACTS_FETCH_ERROR'

export default {
  GET_FOLDERS,
  LOADING_FOLDERS,
  FOLDER_FETCH_ERROR,
  GET_MAILS,
  MAILS_FETCH_ERROR,
  LOADING_MAILS,
  SELECT_FOLDER,
  SELECT_MAIL,
  GET_MAIL,
  LOADING_MAIL,
  MAIL_FETCH_ERROR,
  NEW_MAIL,
  GET_CONTACTS,
  LOADING_CONTACTS,
  CONTACTS_FETCH_ERROR
};
